// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForBulkAddTagsToPublisherZman implements pgx.CopyFromSource.
type iteratorForBulkAddTagsToPublisherZman struct {
	rows                 []BulkAddTagsToPublisherZmanParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkAddTagsToPublisherZman) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkAddTagsToPublisherZman) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PublisherZmanID,
		r.rows[0].TagID,
		r.rows[0].IsNegated,
	}, nil
}

func (r iteratorForBulkAddTagsToPublisherZman) Err() error {
	return nil
}

// Bulk insert tags for a publisher zman (with is_negated)
func (q *Queries) BulkAddTagsToPublisherZman(ctx context.Context, arg []BulkAddTagsToPublisherZmanParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"publisher_zman_tags"}, []string{"publisher_zman_id", "tag_id", "is_negated"}, &iteratorForBulkAddTagsToPublisherZman{rows: arg})
}
