// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coverage.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoverage = `-- name: CreateCoverage :one
INSERT INTO publisher_coverage (publisher_id, coverage_level, country_code, region, city_id, priority, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, publisher_id, coverage_level, country_code, region, city_id,
          priority, is_active, created_at, updated_at
`

type CreateCoverageParams struct {
	PublisherID   string      `json:"publisher_id"`
	CoverageLevel string      `json:"coverage_level"`
	CountryCode   *string     `json:"country_code"`
	Region        *string     `json:"region"`
	CityID        pgtype.UUID `json:"city_id"`
	Priority      *int32      `json:"priority"`
	IsActive      *bool       `json:"is_active"`
}

func (q *Queries) CreateCoverage(ctx context.Context, arg CreateCoverageParams) (PublisherCoverage, error) {
	row := q.db.QueryRow(ctx, createCoverage,
		arg.PublisherID,
		arg.CoverageLevel,
		arg.CountryCode,
		arg.Region,
		arg.CityID,
		arg.Priority,
		arg.IsActive,
	)
	var i PublisherCoverage
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.CoverageLevel,
		&i.CountryCode,
		&i.Region,
		&i.CityID,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoverage = `-- name: DeleteCoverage :exec
DELETE FROM publisher_coverage
WHERE id = $1
`

func (q *Queries) DeleteCoverage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCoverage, id)
	return err
}

const deleteCoverageByPublisher = `-- name: DeleteCoverageByPublisher :exec
DELETE FROM publisher_coverage
WHERE publisher_id = $1
`

func (q *Queries) DeleteCoverageByPublisher(ctx context.Context, publisherID string) error {
	_, err := q.db.Exec(ctx, deleteCoverageByPublisher, publisherID)
	return err
}

const getCitiesCoveredCount = `-- name: GetCitiesCoveredCount :one
SELECT COALESCE(SUM(
    CASE coverage_level
        WHEN 'city' THEN 1
        WHEN 'region' THEN (
            SELECT COUNT(*) FROM cities c
            JOIN geo_countries co ON c.country_id = co.id
            LEFT JOIN geo_regions r ON c.region_id = r.id
            WHERE co.code = pc.country_code AND r.name = pc.region
        )
        WHEN 'country' THEN (
            SELECT COUNT(*) FROM cities c
            JOIN geo_countries co ON c.country_id = co.id
            WHERE co.code = pc.country_code
        )
        ELSE 0
    END
), 0)::int
FROM publisher_coverage pc
WHERE publisher_id = $1 AND is_active = true
`

func (q *Queries) GetCitiesCoveredCount(ctx context.Context, publisherID string) (int32, error) {
	row := q.db.QueryRow(ctx, getCitiesCoveredCount, publisherID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getCoverageCountByPublisher = `-- name: GetCoverageCountByPublisher :one
SELECT COUNT(*)
FROM publisher_coverage
WHERE publisher_id = $1 AND is_active = true
`

func (q *Queries) GetCoverageCountByPublisher(ctx context.Context, publisherID string) (int64, error) {
	row := q.db.QueryRow(ctx, getCoverageCountByPublisher, publisherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublisherCoverage = `-- name: GetPublisherCoverage :many

SELECT id, publisher_id, coverage_level, country_code, region, city_id,
       priority, is_active, created_at, updated_at
FROM publisher_coverage
WHERE publisher_id = $1 AND is_active = true
ORDER BY priority DESC, created_at DESC
`

// Coverage SQL Queries
// SQLc will generate type-safe Go code from these queries
func (q *Queries) GetPublisherCoverage(ctx context.Context, publisherID string) ([]PublisherCoverage, error) {
	rows, err := q.db.Query(ctx, getPublisherCoverage, publisherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublisherCoverage{}
	for rows.Next() {
		var i PublisherCoverage
		if err := rows.Scan(
			&i.ID,
			&i.PublisherID,
			&i.CoverageLevel,
			&i.CountryCode,
			&i.Region,
			&i.CityID,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublisherCoverageByID = `-- name: GetPublisherCoverageByID :one
SELECT id, publisher_id, coverage_level, country_code, region, city_id,
       priority, is_active, created_at, updated_at
FROM publisher_coverage
WHERE id = $1
`

func (q *Queries) GetPublisherCoverageByID(ctx context.Context, id string) (PublisherCoverage, error) {
	row := q.db.QueryRow(ctx, getPublisherCoverageByID, id)
	var i PublisherCoverage
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.CoverageLevel,
		&i.CountryCode,
		&i.Region,
		&i.CityID,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCoverage = `-- name: UpdateCoverage :one
UPDATE publisher_coverage
SET coverage_level = COALESCE($2, coverage_level),
    country_code = COALESCE($3, country_code),
    region = COALESCE($4, region),
    city_id = COALESCE($5, city_id),
    priority = COALESCE($6, priority),
    is_active = COALESCE($7, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, publisher_id, coverage_level, country_code, region, city_id,
          priority, is_active, created_at, updated_at
`

type UpdateCoverageParams struct {
	ID            string      `json:"id"`
	CoverageLevel *string     `json:"coverage_level"`
	CountryCode   *string     `json:"country_code"`
	Region        *string     `json:"region"`
	CityID        pgtype.UUID `json:"city_id"`
	Priority      *int32      `json:"priority"`
	IsActive      *bool       `json:"is_active"`
}

func (q *Queries) UpdateCoverage(ctx context.Context, arg UpdateCoverageParams) (PublisherCoverage, error) {
	row := q.db.QueryRow(ctx, updateCoverage,
		arg.ID,
		arg.CoverageLevel,
		arg.CountryCode,
		arg.Region,
		arg.CityID,
		arg.Priority,
		arg.IsActive,
	)
	var i PublisherCoverage
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.CoverageLevel,
		&i.CountryCode,
		&i.Region,
		&i.CityID,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
