// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publishers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishers = `-- name: CountPublishers :one
SELECT COUNT(*)
FROM publishers
WHERE ($1::text IS NULL OR region_id = $1)
`

func (q *Queries) CountPublishers(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (name, email, status, clerk_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_user_id, name, email, description, bio,
          website, logo_url, logo_data, status, created_at, updated_at
`

type CreatePublisherParams struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Status      string  `json:"status"`
	ClerkUserID *string `json:"clerk_user_id"`
}

type CreatePublisherRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (CreatePublisherRow, error) {
	row := q.db.QueryRow(ctx, createPublisher,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.ClerkUserID,
	)
	var i CreatePublisherRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE FROM publishers
WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePublisher, id)
	return err
}

const getPublisherAlgorithmSummary = `-- name: GetPublisherAlgorithmSummary :one
SELECT
    CASE WHEN is_active THEN 'published' ELSE 'draft' END as status,
    name,
    TO_CHAR(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as updated_at
FROM algorithms
WHERE publisher_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

type GetPublisherAlgorithmSummaryRow struct {
	Status    string `json:"status"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) GetPublisherAlgorithmSummary(ctx context.Context, publisherID string) (GetPublisherAlgorithmSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPublisherAlgorithmSummary, publisherID)
	var i GetPublisherAlgorithmSummaryRow
	err := row.Scan(&i.Status, &i.Name, &i.UpdatedAt)
	return i, err
}

const getPublisherBasic = `-- name: GetPublisherBasic :one
SELECT id, name, status
FROM publishers
WHERE id = $1
`

type GetPublisherBasicRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) GetPublisherBasic(ctx context.Context, id string) (GetPublisherBasicRow, error) {
	row := q.db.QueryRow(ctx, getPublisherBasic, id)
	var i GetPublisherBasicRow
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getPublisherBasicByClerkUserID = `-- name: GetPublisherBasicByClerkUserID :one
SELECT id, name, status
FROM publishers
WHERE clerk_user_id = $1
`

type GetPublisherBasicByClerkUserIDRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) GetPublisherBasicByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherBasicByClerkUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPublisherBasicByClerkUserID, clerkUserID)
	var i GetPublisherBasicByClerkUserIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getPublisherByClerkUserID = `-- name: GetPublisherByClerkUserID :one
SELECT id
FROM publishers
WHERE clerk_user_id = $1
`

func (q *Queries) GetPublisherByClerkUserID(ctx context.Context, clerkUserID *string) (string, error) {
	row := q.db.QueryRow(ctx, getPublisherByClerkUserID, clerkUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPublisherByID = `-- name: GetPublisherByID :one

SELECT id, clerk_user_id, name, email, description, bio,
       website, logo_url, logo_data, status, created_at, updated_at
FROM publishers
WHERE id = $1
`

type GetPublisherByIDRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Publishers SQL Queries
// SQLc will generate type-safe Go code from these queries
func (q *Queries) GetPublisherByID(ctx context.Context, id string) (GetPublisherByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublisherByID, id)
	var i GetPublisherByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublisherCoverageCount = `-- name: GetPublisherCoverageCount :one
SELECT COUNT(*)
FROM publisher_coverage
WHERE publisher_id = $1 AND is_active = true
`

func (q *Queries) GetPublisherCoverageCount(ctx context.Context, publisherID string) (int64, error) {
	row := q.db.QueryRow(ctx, getPublisherCoverageCount, publisherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublisherDashboardSummary = `-- name: GetPublisherDashboardSummary :one
SELECT
    p.name,
    p.status = 'verified' as is_verified,
    p.status
FROM publishers p
WHERE p.id = $1
`

type GetPublisherDashboardSummaryRow struct {
	Name       string `json:"name"`
	IsVerified bool   `json:"is_verified"`
	Status     string `json:"status"`
}

func (q *Queries) GetPublisherDashboardSummary(ctx context.Context, id string) (GetPublisherDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPublisherDashboardSummary, id)
	var i GetPublisherDashboardSummaryRow
	err := row.Scan(&i.Name, &i.IsVerified, &i.Status)
	return i, err
}

const getPublisherFullByClerkUserID = `-- name: GetPublisherFullByClerkUserID :one
SELECT id, clerk_user_id, name, email, description, bio,
       website, logo_url, logo_data, status, created_at, updated_at
FROM publishers
WHERE clerk_user_id = $1
`

type GetPublisherFullByClerkUserIDRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublisherFullByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherFullByClerkUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPublisherFullByClerkUserID, clerkUserID)
	var i GetPublisherFullByClerkUserIDRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishers = `-- name: ListPublishers :many
SELECT id, name, status, created_at
FROM publishers
WHERE ($1::text IS NULL OR region_id = $1)
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListPublishersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPublishersRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPublishers(ctx context.Context, arg ListPublishersParams) ([]ListPublishersRow, error) {
	rows, err := q.db.Query(ctx, listPublishers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishersRow{}
	for rows.Next() {
		var i ListPublishersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishersByIDs = `-- name: ListPublishersByIDs :many
SELECT id, name, status
FROM publishers
WHERE id = ANY($1::text[])
ORDER BY name
`

type ListPublishersByIDsRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) ListPublishersByIDs(ctx context.Context, dollar_1 []string) ([]ListPublishersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishersByIDsRow{}
	for rows.Next() {
		var i ListPublishersByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisherLogo = `-- name: UpdatePublisherLogo :one
UPDATE publishers
SET logo_data = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, logo_data
`

type UpdatePublisherLogoParams struct {
	ID       string  `json:"id"`
	LogoData *string `json:"logo_data"`
}

type UpdatePublisherLogoRow struct {
	ID       string  `json:"id"`
	LogoData *string `json:"logo_data"`
}

func (q *Queries) UpdatePublisherLogo(ctx context.Context, arg UpdatePublisherLogoParams) (UpdatePublisherLogoRow, error) {
	row := q.db.QueryRow(ctx, updatePublisherLogo, arg.ID, arg.LogoData)
	var i UpdatePublisherLogoRow
	err := row.Scan(&i.ID, &i.LogoData)
	return i, err
}

const updatePublisherProfile = `-- name: UpdatePublisherProfile :one
UPDATE publishers
SET name = COALESCE($2, name),
    email = COALESCE($3, email),
    website = COALESCE($4, website),
    bio = COALESCE($5, bio),
    updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_user_id, name, email, description, bio,
          website, logo_url, logo_data, status, created_at, updated_at
`

type UpdatePublisherProfileParams struct {
	ID      string  `json:"id"`
	Name    *string `json:"name"`
	Email   *string `json:"email"`
	Website *string `json:"website"`
	Bio     *string `json:"bio"`
}

type UpdatePublisherProfileRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePublisherProfile(ctx context.Context, arg UpdatePublisherProfileParams) (UpdatePublisherProfileRow, error) {
	row := q.db.QueryRow(ctx, updatePublisherProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Website,
		arg.Bio,
	)
	var i UpdatePublisherProfileRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublisherProfileByClerkUserID = `-- name: UpdatePublisherProfileByClerkUserID :one
UPDATE publishers
SET name = COALESCE($2, name),
    email = COALESCE($3, email),
    website = COALESCE($4, website),
    bio = COALESCE($5, bio),
    updated_at = NOW()
WHERE clerk_user_id = $1
RETURNING id, clerk_user_id, name, email, description, bio,
          website, logo_url, logo_data, status, created_at, updated_at
`

type UpdatePublisherProfileByClerkUserIDParams struct {
	ClerkUserID *string `json:"clerk_user_id"`
	Name        *string `json:"name"`
	Email       *string `json:"email"`
	Website     *string `json:"website"`
	Bio         *string `json:"bio"`
}

type UpdatePublisherProfileByClerkUserIDRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePublisherProfileByClerkUserID(ctx context.Context, arg UpdatePublisherProfileByClerkUserIDParams) (UpdatePublisherProfileByClerkUserIDRow, error) {
	row := q.db.QueryRow(ctx, updatePublisherProfileByClerkUserID,
		arg.ClerkUserID,
		arg.Name,
		arg.Email,
		arg.Website,
		arg.Bio,
	)
	var i UpdatePublisherProfileByClerkUserIDRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublisherStatus = `-- name: UpdatePublisherStatus :one
UPDATE publishers
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_user_id, name, email, description, bio,
          website, logo_url, logo_data, status, created_at, updated_at
`

type UpdatePublisherStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

type UpdatePublisherStatusRow struct {
	ID          string             `json:"id"`
	ClerkUserID *string            `json:"clerk_user_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Description *string            `json:"description"`
	Bio         *string            `json:"bio"`
	Website     *string            `json:"website"`
	LogoUrl     *string            `json:"logo_url"`
	LogoData    *string            `json:"logo_data"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePublisherStatus(ctx context.Context, arg UpdatePublisherStatusParams) (UpdatePublisherStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePublisherStatus, arg.ID, arg.Status)
	var i UpdatePublisherStatusRow
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.Bio,
		&i.Website,
		&i.LogoUrl,
		&i.LogoData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
