// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id string) error
	AddMasterZmanFromRequest(ctx context.Context, id string) (AddMasterZmanFromRequestRow, error)
	AdminCountAlgorithms(ctx context.Context, dollar_1 string) (int64, error)
	AdminCountPublishers(ctx context.Context, dollar_1 string) (int64, error)
	AdminDeletePublisher(ctx context.Context, id string) error
	AdminGetPublisher(ctx context.Context, id string) (AdminGetPublisherRow, error)
	// Admin Statistics --
	AdminGetStatistics(ctx context.Context) (AdminGetStatisticsRow, error)
	// Admin Algorithm Management --
	AdminListAlgorithms(ctx context.Context, arg AdminListAlgorithmsParams) ([]AdminListAlgorithmsRow, error)
	// Admin SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Admin Publisher Management --
	AdminListPublishers(ctx context.Context, arg AdminListPublishersParams) ([]AdminListPublishersRow, error)
	AdminUpdatePublisherStatus(ctx context.Context, arg AdminUpdatePublisherStatusParams) (AdminUpdatePublisherStatusRow, error)
	// Publish algorithm --
	ArchiveActiveAlgorithms(ctx context.Context, publisherID string) error
	// Browse public zmanim --
	BrowsePublicZmanim(ctx context.Context, arg BrowsePublicZmanimParams) ([]BrowsePublicZmanimRow, error)
	CompleteOnboarding(ctx context.Context, publisherID string) (string, error)
	CountCities(ctx context.Context, arg CountCitiesParams) (int64, error)
	CountPendingInvitationsForEmail(ctx context.Context, arg CountPendingInvitationsForEmailParams) (int64, error)
	CountPublisherZmanim(ctx context.Context, publisherID string) (int64, error)
	CountPublishers(ctx context.Context, dollar_1 string) (int64, error)
	// Create or update algorithm --
	CreateAlgorithm(ctx context.Context, arg CreateAlgorithmParams) (CreateAlgorithmRow, error)
	CreateCoverage(ctx context.Context, arg CreateCoverageParams) (PublisherCoverage, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (string, error)
	CreateOnboardingState(ctx context.Context, publisherID string) (PublisherOnboarding, error)
	CreatePublisher(ctx context.Context, arg CreatePublisherParams) (CreatePublisherRow, error)
	CreatePublisherZman(ctx context.Context, arg CreatePublisherZmanParams) (CreatePublisherZmanRow, error)
	CreatePublisherZmanFromRegistry(ctx context.Context, arg CreatePublisherZmanFromRegistryParams) (CreatePublisherZmanFromRegistryRow, error)
	// ============================================
	// ZMAN REGISTRY REQUESTS
	// ============================================
	CreateZmanRegistryRequest(ctx context.Context, arg CreateZmanRegistryRequestParams) (CreateZmanRegistryRequestRow, error)
	CreateZmanVersion(ctx context.Context, arg CreateZmanVersionParams) (PublisherZmanVersion, error)
	DeleteCoverage(ctx context.Context, id string) error
	DeleteCoverageByPublisher(ctx context.Context, publisherID string) error
	DeleteInvitation(ctx context.Context, id string) error
	DeletePublisher(ctx context.Context, id string) error
	DeletePublisherZman(ctx context.Context, arg DeletePublisherZmanParams) (string, error)
	DeprecateAlgorithmVersion(ctx context.Context, arg DeprecateAlgorithmVersionParams) (int64, error)
	ExpireInvitation(ctx context.Context, id string) error
	GetAlgorithmByID(ctx context.Context, arg GetAlgorithmByIDParams) (GetAlgorithmByIDRow, error)
	// Algorithm versions --
	GetAlgorithmVersions(ctx context.Context, publisherID string) ([]GetAlgorithmVersionsRow, error)
	// ============================================
	// ASTRONOMICAL PRIMITIVES QUERIES
	// ============================================
	GetAllAstronomicalPrimitives(ctx context.Context) ([]AstronomicalPrimitive, error)
	// Master Zmanim Registry SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// ============================================
	// MASTER REGISTRY QUERIES
	// ============================================
	GetAllMasterZmanim(ctx context.Context) ([]GetAllMasterZmanimRow, error)
	// ============================================
	// TAG QUERIES
	// ============================================
	GetAllTags(ctx context.Context) ([]ZmanTag, error)
	GetAstronomicalPrimitiveByName(ctx context.Context, variableName string) (AstronomicalPrimitive, error)
	GetAstronomicalPrimitivesByCategory(ctx context.Context, category string) ([]AstronomicalPrimitive, error)
	// Returns primitives with category for grouping in UI
	GetAstronomicalPrimitivesGrouped(ctx context.Context) ([]AstronomicalPrimitive, error)
	GetCitiesCoveredCount(ctx context.Context, publisherID string) (int32, error)
	GetCitiesForCoverage(ctx context.Context, arg GetCitiesForCoverageParams) ([]GetCitiesForCoverageRow, error)
	GetCityByID(ctx context.Context, id string) (GetCityByIDRow, error)
	GetCityByName(ctx context.Context, name string) (GetCityByNameRow, error)
	GetCountries(ctx context.Context) ([]GetCountriesRow, error)
	GetCoverageCountByPublisher(ctx context.Context, publisherID string) (int64, error)
	GetDeletedPublisherZmanim(ctx context.Context, publisherID string) ([]GetDeletedPublisherZmanimRow, error)
	GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error)
	GetMasterZmanByID(ctx context.Context, id string) (GetMasterZmanByIDRow, error)
	GetMasterZmanByKey(ctx context.Context, zmanKey string) (GetMasterZmanByKeyRow, error)
	GetMasterZmanimByCategory(ctx context.Context, timeCategory string) ([]GetMasterZmanimByCategoryRow, error)
	GetMasterZmanimByTag(ctx context.Context, name string) ([]GetMasterZmanimByTagRow, error)
	GetMasterZmanimGroupedByCategory(ctx context.Context) ([]GetMasterZmanimGroupedByCategoryRow, error)
	// Onboarding related --
	GetOnboardingState(ctx context.Context, publisherID string) (PublisherOnboarding, error)
	// Publisher Invitations --
	GetPendingInvitations(ctx context.Context, publisherID pgtype.UUID) ([]GetPendingInvitationsRow, error)
	GetPublisherActiveAlgorithm(ctx context.Context, publisherID string) (GetPublisherActiveAlgorithmRow, error)
	GetPublisherAlgorithmSummary(ctx context.Context, publisherID string) (GetPublisherAlgorithmSummaryRow, error)
	GetPublisherBasic(ctx context.Context, id string) (GetPublisherBasicRow, error)
	GetPublisherBasicByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherBasicByClerkUserIDRow, error)
	GetPublisherByClerkUserID(ctx context.Context, clerkUserID *string) (string, error)
	// Publishers SQL Queries
	// SQLc will generate type-safe Go code from these queries
	GetPublisherByID(ctx context.Context, id string) (GetPublisherByIDRow, error)
	// Coverage SQL Queries
	// SQLc will generate type-safe Go code from these queries
	GetPublisherCoverage(ctx context.Context, publisherID string) ([]PublisherCoverage, error)
	GetPublisherCoverageByID(ctx context.Context, id string) (PublisherCoverage, error)
	GetPublisherCoverageCount(ctx context.Context, publisherID string) (int64, error)
	GetPublisherDashboardSummary(ctx context.Context, id string) (GetPublisherDashboardSummaryRow, error)
	// Algorithms SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Get algorithm for publisher --
	GetPublisherDraftAlgorithm(ctx context.Context, publisherID string) (GetPublisherDraftAlgorithmRow, error)
	GetPublisherFullByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherFullByClerkUserIDRow, error)
	// Team Management --
	GetPublisherOwner(ctx context.Context, id string) (*string, error)
	GetPublisherZmanByKey(ctx context.Context, arg GetPublisherZmanByKeyParams) (GetPublisherZmanByKeyRow, error)
	GetPublisherZmanWithRegistry(ctx context.Context, arg GetPublisherZmanWithRegistryParams) (GetPublisherZmanWithRegistryRow, error)
	// Zmanim SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Publisher Zmanim --
	GetPublisherZmanim(ctx context.Context, publisherID string) ([]GetPublisherZmanimRow, error)
	// ============================================
	// PUBLISHER ZMANIM WITH REGISTRY (new model)
	// ============================================
	GetPublisherZmanimWithRegistry(ctx context.Context, publisherID string) ([]GetPublisherZmanimWithRegistryRow, error)
	GetRegionsByCountry(ctx context.Context, countryCode string) ([]*string, error)
	GetTagByName(ctx context.Context, name string) (ZmanTag, error)
	GetTagsByType(ctx context.Context, tagType string) ([]ZmanTag, error)
	GetTagsForMasterZman(ctx context.Context, masterZmanID string) ([]ZmanTag, error)
	GetZmanDefinitionByKey(ctx context.Context, key string) (GetZmanDefinitionByKeyRow, error)
	// Zman Definitions (Global) --
	GetZmanDefinitions(ctx context.Context) ([]GetZmanDefinitionsRow, error)
	GetZmanRegistryRequestByID(ctx context.Context, id string) (ZmanRegistryRequest, error)
	GetZmanRegistryRequests(ctx context.Context, status *string) ([]ZmanRegistryRequest, error)
	GetZmanVersion(ctx context.Context, arg GetZmanVersionParams) (PublisherZmanVersion, error)
	// ============================================
	// VERSION HISTORY QUERIES
	// ============================================
	GetZmanVersionHistory(ctx context.Context, arg GetZmanVersionHistoryParams) ([]PublisherZmanVersion, error)
	GetZmanimTemplateByKey(ctx context.Context, zmanKey string) (ZmanimTemplate, error)
	// Zmanim Templates --
	GetZmanimTemplates(ctx context.Context) ([]ZmanimTemplate, error)
	GetZmanimTemplatesByKeys(ctx context.Context, dollar_1 []string) ([]ZmanimTemplate, error)
	ImportZmanimFromRegistryByKeys(ctx context.Context, arg ImportZmanimFromRegistryByKeysParams) ([]ImportZmanimFromRegistryByKeysRow, error)
	// Import from templates to publisher --
	ImportZmanimFromTemplates(ctx context.Context, publisherID string) ([]ImportZmanimFromTemplatesRow, error)
	ImportZmanimFromTemplatesByKeys(ctx context.Context, arg ImportZmanimFromTemplatesByKeysParams) ([]ImportZmanimFromTemplatesByKeysRow, error)
	ListCitiesByCountry(ctx context.Context, arg ListCitiesByCountryParams) ([]ListCitiesByCountryRow, error)
	ListCitiesByRegion(ctx context.Context, arg ListCitiesByRegionParams) ([]ListCitiesByRegionRow, error)
	ListPublishers(ctx context.Context, arg ListPublishersParams) ([]ListPublishersRow, error)
	ListPublishersByIDs(ctx context.Context, dollar_1 []string) ([]ListPublishersByIDsRow, error)
	PermanentDeletePublisherZman(ctx context.Context, arg PermanentDeletePublisherZmanParams) error
	PublishAlgorithm(ctx context.Context, arg PublishAlgorithmParams) (PublishAlgorithmRow, error)
	// Bulk publish/unpublish zmanim --
	PublishAllZmanim(ctx context.Context, publisherID string) error
	PublishZmanimByKeys(ctx context.Context, arg PublishZmanimByKeysParams) error
	RestorePublisherZman(ctx context.Context, arg RestorePublisherZmanParams) (RestorePublisherZmanRow, error)
	RollbackZmanToVersion(ctx context.Context, arg RollbackZmanToVersionParams) (RollbackZmanToVersionRow, error)
	// Cities SQL Queries
	// SQLc will generate type-safe Go code from these queries
	SearchCities(ctx context.Context, arg SearchCitiesParams) ([]SearchCitiesRow, error)
	SearchMasterZmanim(ctx context.Context, dollar_1 *string) ([]SearchMasterZmanimRow, error)
	SkipOnboarding(ctx context.Context, publisherID string) (string, error)
	// ============================================
	// SOFT DELETE QUERIES
	// ============================================
	SoftDeletePublisherZman(ctx context.Context, arg SoftDeletePublisherZmanParams) (SoftDeletePublisherZmanRow, error)
	UnpublishAllZmanim(ctx context.Context, publisherID string) error
	UnpublishZmanimByKeys(ctx context.Context, arg UnpublishZmanimByKeysParams) error
	UpdateAlgorithmDraft(ctx context.Context, arg UpdateAlgorithmDraftParams) (UpdateAlgorithmDraftRow, error)
	UpdateCoverage(ctx context.Context, arg UpdateCoverageParams) (PublisherCoverage, error)
	UpdateInvitationToken(ctx context.Context, arg UpdateInvitationTokenParams) error
	UpdateOnboardingState(ctx context.Context, arg UpdateOnboardingStateParams) (PublisherOnboarding, error)
	UpdatePublisherLogo(ctx context.Context, arg UpdatePublisherLogoParams) (UpdatePublisherLogoRow, error)
	UpdatePublisherProfile(ctx context.Context, arg UpdatePublisherProfileParams) (UpdatePublisherProfileRow, error)
	UpdatePublisherProfileByClerkUserID(ctx context.Context, arg UpdatePublisherProfileByClerkUserIDParams) (UpdatePublisherProfileByClerkUserIDRow, error)
	UpdatePublisherStatus(ctx context.Context, arg UpdatePublisherStatusParams) (UpdatePublisherStatusRow, error)
	UpdatePublisherZman(ctx context.Context, arg UpdatePublisherZmanParams) (UpdatePublisherZmanRow, error)
	UpdateZmanCurrentVersion(ctx context.Context, arg UpdateZmanCurrentVersionParams) error
	UpdateZmanRegistryRequestStatus(ctx context.Context, arg UpdateZmanRegistryRequestStatusParams) (ZmanRegistryRequest, error)
}

var _ Querier = (*Queries)(nil)
