#!/bin/bash
# Push Coder template with secrets from local .env files
# This script reads from .env.clerk, .env.resend, .env.mailslurp, .env.openai, .env.claude
# and creates terraform.tfvars, then pushes the template
# Note: Database uses local postgres (no external Supabase needed)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "🚀 Pushing Coder template with secrets..."

# Check for required env files
MISSING_FILES=""
[ ! -f "$PROJECT_ROOT/.env.clerk" ] && MISSING_FILES="$MISSING_FILES .env.clerk"
[ ! -f "$PROJECT_ROOT/.env.resend" ] && MISSING_FILES="$MISSING_FILES .env.resend"
[ ! -f "$PROJECT_ROOT/.env.mailslurp" ] && MISSING_FILES="$MISSING_FILES .env.mailslurp"

if [ -n "$MISSING_FILES" ]; then
    echo "❌ Missing required env files:$MISSING_FILES"
    echo "   Create these files in the project root with your credentials"
    echo "   Use .env.*.example files as templates"
    exit 1
fi

# Check for optional AI env files (required for Epic 4)
OPTIONAL_MISSING=""
[ ! -f "$PROJECT_ROOT/.env.openai" ] && OPTIONAL_MISSING="$OPTIONAL_MISSING .env.openai"
[ ! -f "$PROJECT_ROOT/.env.claude" ] && OPTIONAL_MISSING="$OPTIONAL_MISSING .env.claude"

if [ -n "$OPTIONAL_MISSING" ]; then
    echo "⚠️  Optional AI env files not found:$OPTIONAL_MISSING"
    echo "   AI features (Epic 4) will not work without these keys"
    echo "   Create these files with OPENAI_API_KEY and ANTHROPIC_API_KEY"
fi

# Source required env files
source "$PROJECT_ROOT/.env.clerk"
source "$PROJECT_ROOT/.env.resend"
source "$PROJECT_ROOT/.env.mailslurp"

# Source optional AI env files if they exist
[ -f "$PROJECT_ROOT/.env.openai" ] && source "$PROJECT_ROOT/.env.openai"
[ -f "$PROJECT_ROOT/.env.claude" ] && source "$PROJECT_ROOT/.env.claude"

# Create terraform.tfvars (will be ignored by git)
cat > "$SCRIPT_DIR/terraform.tfvars" << EOF
# Generated by push-template.sh - DO NOT COMMIT
zmanim_branch = "main"
zmanim_repo   = "git@github.com:jcom-dev/zmanim-lab.git"

# Clerk Authentication
clerk_publishable_key = "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
clerk_secret_key      = "$CLERK_SECRET_KEY"
clerk_jwks_url        = "$CLERK_JWKS_URL"
clerk_issuer          = "$CLERK_ISSUER"

# Test Clerk Instance
clerk_test_publishable_key = "$CLERK_TEST_PUBLISHABLE_KEY"
clerk_test_secret_key      = "$CLERK_TEST_SECRET_KEY"

# Email Services
resend_api_key    = "$RESEND_API_KEY"
resend_domain     = "$RESEND_DOMAIN"
resend_from       = "$RESEND_FROM"
mailslurp_api_key = "$MAILSLURP_API_KEY"

# AI Services (Epic 4)
openai_api_key    = "${OPENAI_API_KEY:-}"
anthropic_api_key = "${ANTHROPIC_API_KEY:-}"
EOF

echo "✅ Created terraform.tfvars from env files"

# Copy Claude Code config if it exists (for AI-assisted development)
if [ -f "$HOME/.claude.json" ]; then
    cp "$HOME/.claude.json" "$SCRIPT_DIR/claude.json"
    echo "✅ Copied ~/.claude.json to template directory"
else
    echo "ℹ️  No ~/.claude.json found (optional - for Claude Code config)"
fi

# Verify Dockerfile exists for custom postgres image
if [ ! -f "$SCRIPT_DIR/docker/Dockerfile.postgres" ]; then
    echo "❌ Missing Dockerfile.postgres in .coder/docker/"
    echo "   This is required for PostgreSQL 17 + PostGIS + pgvector"
    exit 1
fi
echo "✅ Found custom PostgreSQL Dockerfile (PostGIS + pgvector)"

# Push the template
echo "📤 Pushing template to Coder..."
echo "   Note: Terraform will build PostgreSQL 17 + PostGIS + pgvector image"
cd "$SCRIPT_DIR"
coder templates push zmanim-lab --directory . --yes

echo ""
echo "✅ Template pushed successfully!"
echo ""
echo "To create a workspace:"
echo "  coder create zmanim-lab-dev --template zmanim-lab"
