#!/bin/bash
set -e

# Zmanim Lab Development Environment Startup Script
# This script initializes the development environment for the monorepo

echo "🚀 Starting Zmanim Lab Development Environment Setup..."

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Fix workspace directory ownership (needed for Docker volumes)
sudo chown -R coder:coder /home/coder/workspace

# Change to workspace directory
cd /home/coder/workspace

# Step 1: Install Go 1.25.4 (latest)
print_status "Installing Go 1.25.4..."
if ! command -v go &> /dev/null || [[ $(go version | grep -o '1\.25\.4') == "" ]]; then
    wget -q https://go.dev/dl/go1.25.4.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf go1.25.4.linux-amd64.tar.gz
    rm go1.25.4.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    print_success "Go 1.25.4 installed"
else
    print_success "Go 1.25.4 already installed ($(go version))"
fi

# Step 2: Install Node.js 24.x LTS (Krypton - latest LTS)
print_status "Installing Node.js 24.x LTS..."
if ! command -v node &> /dev/null || [[ $(node --version | grep -o 'v24') == "" ]]; then
    curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
    sudo apt-get install -y nodejs
    print_success "Node.js 24.x LTS installed"
else
    print_success "Node.js 24.x LTS already installed ($(node --version))"
fi

# Step 3: Clone repository if it doesn't exist (monorepo)
print_status "Checking repository..."

# Add GitHub to known hosts
mkdir -p ~/.ssh
ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null

if [ ! -d "zmanim-lab/.git" ]; then
    print_status "Cloning zmanim-lab repository..."
    rm -rf zmanim-lab 2>/dev/null
    git clone ${ZMANIM_REPO:-git@github.com:jcom-dev/zmanim-lab.git} zmanim-lab || print_warning "Failed to clone zmanim-lab"
else
    print_success "zmanim-lab already cloned"
fi

# Checkout specified branch
if [ -n "${ZMANIM_BRANCH}" ] && [ "${ZMANIM_BRANCH}" != "main" ]; then
    print_status "Checking out branch '${ZMANIM_BRANCH}'..."
    cd zmanim-lab
    if git fetch origin "${ZMANIM_BRANCH}" 2>/dev/null && git checkout "${ZMANIM_BRANCH}" 2>/dev/null; then
        print_success "Checked out ${ZMANIM_BRANCH}"
    else
        print_warning "Branch ${ZMANIM_BRANCH} not found, staying on default"
    fi
    cd /home/coder/workspace
fi

# Step 4: Install Go dependencies
print_status "Installing Go dependencies..."
if [ -d "zmanim-lab/api" ]; then
    cd zmanim-lab/api
    go mod download || print_warning "Failed to download Go dependencies"
    cd /home/coder/workspace
    print_success "Go dependencies installed"
fi

# Step 5: Install Node.js dependencies
print_status "Installing Node.js dependencies..."
if [ -d "zmanim-lab/web" ]; then
    cd zmanim-lab/web
    npm install || print_warning "Failed to install web dependencies"
    cd /home/coder/workspace
    print_success "Web dependencies installed"
fi

# Step 6: Install Playwright browsers for E2E testing
print_status "Installing Playwright browsers..."
if [ -d "zmanim-lab/web" ]; then
    cd zmanim-lab/web
    npx playwright install --with-deps chromium || print_warning "Failed to install Playwright browsers"
    cd /home/coder/workspace
    print_success "Playwright browsers installed"
fi

# Step 7: Create .env files from Coder template variables
print_status "Setting up environment files from Coder variables..."
cd zmanim-lab

# Create api/.env from environment variables (set by Coder template)
if [ -n "$DATABASE_URL" ]; then
    cat > api/.env << ENVEOF
# Generated by Coder workspace startup

# Database & Cache (local Coder containers via Docker network)
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}

# Supabase (for storage/auth features)
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

# Authentication
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
CLERK_ISSUER=${CLERK_ISSUER}

# Server Configuration
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001,https://localhost:3000,https://localhost:3001,https://127.0.0.1:3000,https://127.0.0.1:3001}
PORT=8080
GO_ENV=development

# Email
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success "api/.env created from Coder variables"
else
    print_warning "DATABASE_URL not set - copy .env.example to api/.env and configure"
    [ -f ".env.example" ] && [ ! -f "api/.env" ] && cp .env.example api/.env
fi

# Create web/.env.local from environment variables (set by Coder template)
if [ -n "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
    cat > web/.env.local << ENVEOF
# Generated by Coder workspace startup

# Production Authentication
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}

# Test Authentication (Clerk TEST instance)
CLERK_TEST_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-}
CLERK_TEST_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-}

# API & Database
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

# Email
MAILSLURP_API_KEY=${MAILSLURP_API_KEY:-}
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success "web/.env.local created from Coder variables"
else
    print_warning "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY not set - copy .env.example to web/.env.local and configure"
    [ -f ".env.example" ] && [ ! -f "web/.env.local" ] && cp .env.example web/.env.local
fi

# Create tests/.env for E2E testing with local database and cache
print_status "Setting up E2E test environment..."
if [ -n "$DATABASE_URL" ]; then
    cat > tests/.env << ENVEOF
# Generated by Coder workspace startup
# Application URL
BASE_URL=http://localhost:3001

# Clerk TEST Instance (for E2E tests)
CLERK_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-${CLERK_SECRET_KEY}}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}

# Database (local PostgreSQL via Docker network)
DATABASE_URL=${DATABASE_URL}
SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

# Cache (local Redis via Docker network)
REDIS_URL=${REDIS_URL}

# MailSlurp Configuration (for email testing)
MAILSLURP_API_KEY=${MAILSLURP_API_KEY:-}

# Skip cleanup after tests (useful for debugging)
# SKIP_CLEANUP=true
ENVEOF
    print_success "tests/.env created with local database and cache"

    # Display connection info
    echo ""
    print_status "Environment configured:"
    echo "  - Database: ${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}"
    echo "  - Redis: ${REDIS_HOST:-redis}:${REDIS_PORT:-6379}"
    echo "  - Clerk: ${CLERK_TEST_SECRET_KEY:+TEST instance}${CLERK_TEST_SECRET_KEY:-using LIVE instance}"
    echo "  - MailSlurp: ${MAILSLURP_API_KEY:+configured}${MAILSLURP_API_KEY:-not configured}"
else
    print_warning "DATABASE_URL not set - copy .env.example to tests/.env and configure"
    [ -f "tests/.env.example" ] && [ ! -f "tests/.env" ] && cp tests/.env.example tests/.env
fi

cd /home/coder/workspace

# Step 8: Install nano text editor
print_status "Installing nano text editor..."
if ! command -v nano &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y nano > /dev/null 2>&1
    print_success "nano installed"
else
    print_success "nano already installed"
fi

# Step 8b: Install PostgreSQL client
print_status "Installing PostgreSQL client..."
if ! command -v psql &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y postgresql-client > /dev/null 2>&1
    print_success "PostgreSQL client installed"
else
    print_success "PostgreSQL client already installed"
fi

# Step 8c: Install Redis client
print_status "Installing Redis client..."
if ! command -v redis-cli &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y redis-tools > /dev/null 2>&1
    print_success "Redis client installed"
else
    print_success "Redis client already installed"
fi

# Step 8d: Install network utilities (ping, nslookup, telnet)
print_status "Installing network utilities..."
sudo apt-get update -qq && sudo apt-get install -y iputils-ping dnsutils telnet net-tools iproute2 > /dev/null 2>&1
print_success "Network utilities installed (ping, nslookup, telnet)"

# Step 9: Install tmux for service management
print_status "Installing tmux..."
if ! command -v tmux &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y tmux > /dev/null 2>&1
    print_success "tmux installed"
else
    print_success "tmux already installed"
fi

# Step 10: Install useful development utilities
print_status "Installing development utilities (jq, tree, htop, ncdu, vim)..."
sudo apt-get update -qq && sudo apt-get install -y \
    jq \
    tree \
    htop \
    ncdu \
    vim \
    iproute2 \
    > /dev/null 2>&1
print_success "Development utilities installed"

# Step 10b: Install Jest globally for testing
print_status "Installing Jest globally..."
if ! npm list -g jest &> /dev/null; then
    sudo npm install -g jest
    print_success "Jest installed globally"
else
    print_success "Jest already installed globally"
fi

# Step 10c: Install Fly.io CLI
print_status "Installing Fly.io CLI..."
if ! command -v flyctl &> /dev/null; then
    curl -L https://fly.io/install.sh | sh
    # Add to PATH for current session
    export FLYCTL_INSTALL="/home/coder/.fly"
    export PATH="$FLYCTL_INSTALL/bin:$PATH"
    echo 'export FLYCTL_INSTALL="/home/coder/.fly"' >> ~/.bashrc
    echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> ~/.bashrc
    print_success "Fly.io CLI installed"
else
    print_success "Fly.io CLI already installed"
fi

# Step 10d: Install uv (Python package manager)
print_status "Installing uv (Python package manager)..."
if ! command -v uv &> /dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # Add to PATH for current session
    export PATH="$HOME/.local/bin:$PATH"
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    print_success "uv installed"
else
    print_success "uv already installed"
fi

# Step 11: Install Claude Code CLI
print_status "Installing Claude Code..."
if ! command -v claude &> /dev/null; then
    curl -fsSL https://claude.ai/install.sh | bash
    # Add to PATH for current session
    export PATH="$HOME/.claude/bin:$PATH"
    echo 'export PATH="$HOME/.claude/bin:$PATH"' >> ~/.bashrc
    print_success "Claude Code installed"
else
    print_success "Claude Code already installed"
fi

# Step 12: Add claude alias to skip permissions
print_status "Adding claude alias to skip permissions..."
echo "alias claude='claude --dangerously-skip-permissions'" >> ~/.bashrc
print_success "Claude alias added"

# Step 12b: Copy Claude Code config if included in template
if [ -f "/home/coder/workspace/zmanim-lab/.coder/claude.json" ]; then
    print_status "Copying Claude Code config..."
    cp /home/coder/workspace/zmanim-lab/.coder/claude.json ~/.claude.json
    print_success "~/.claude.json copied from template"
fi

# Step 12c: Copy API key env files from Coder secrets
print_status "Setting up API key environment files..."
cd /home/coder/workspace/zmanim-lab

# Clerk Authentication (required by push-template.sh)
if [ -n "$CLERK_SECRET_KEY" ]; then
    cat > .env.clerk << ENVEOF
# Clerk Authentication

# Production Instance
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
CLERK_ISSUER=${CLERK_ISSUER}

# Test Instance (for E2E testing)
CLERK_TEST_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-}
CLERK_TEST_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-}
ENVEOF
    print_success ".env.clerk created from Coder variables"
else
    print_warning "CLERK_SECRET_KEY not set - copy .env.clerk.example to .env.clerk and configure"
    [ -f ".env.clerk.example" ] && [ ! -f ".env.clerk" ] && cp .env.clerk.example .env.clerk
fi

# Resend Email Service (required by push-template.sh)
if [ -n "$RESEND_API_KEY" ]; then
    cat > .env.resend << ENVEOF
# Resend Email Service

RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success ".env.resend created from Coder variables"
else
    print_warning "RESEND_API_KEY not set - copy .env.resend.example to .env.resend and configure"
    [ -f ".env.resend.example" ] && [ ! -f ".env.resend" ] && cp .env.resend.example .env.resend
fi

# MailSlurp Email Testing (required by push-template.sh)
if [ -n "$MAILSLURP_API_KEY" ]; then
    cat > .env.mailslurp << ENVEOF
# MailSlurp Email Testing

MAILSLURP_API_KEY=${MAILSLURP_API_KEY}
ENVEOF
    print_success ".env.mailslurp created from Coder variables"
else
    print_warning "MAILSLURP_API_KEY not set - copy .env.mailslurp.example to .env.mailslurp and configure"
    [ -f ".env.mailslurp.example" ] && [ ! -f ".env.mailslurp" ] && cp .env.mailslurp.example .env.mailslurp
fi

# OpenAI API Key (for RAG embeddings)
if [ -n "$OPENAI_API_KEY" ]; then
    cat > .env.openai << ENVEOF
# OpenAI API Key
# Used for: RAG embeddings (text-embedding-3-small) in Epic 4

OPENAI_API_KEY=${OPENAI_API_KEY}
ENVEOF
    print_success ".env.openai created from Coder variables"
else
    print_warning "OPENAI_API_KEY not set - copy .env.openai.example to .env.openai and configure"
    [ -f ".env.openai.example" ] && [ ! -f ".env.openai" ] && cp .env.openai.example .env.openai
fi

# Anthropic/Claude API Key (for AI formula generation)
if [ -n "$ANTHROPIC_API_KEY" ]; then
    cat > .env.claude << ENVEOF
# Anthropic API Key (Claude)
# Used for: AI formula generation and explanations in Epic 4

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENVEOF
    print_success ".env.claude created from Coder variables"
else
    print_warning "ANTHROPIC_API_KEY not set - copy .env.claude.example to .env.claude and configure"
    [ -f ".env.claude.example" ] && [ ! -f ".env.claude" ] && cp .env.claude.example .env.claude
fi

cd /home/coder/workspace

# Step 13: Configure git user identity (with Coder variable overrides)
print_status "Configuring git user identity..."
GIT_USER_NAME="${GIT_USER_NAME:-Daniel Niasoff}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-4070285+dniasoff@users.noreply.github.com}"

git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
print_success "Git user configured: $GIT_USER_NAME <$GIT_USER_EMAIL>"

# Step 14: Display status
echo ""
echo "=========================================="
echo "✅ Zmanim Lab Development Environment Ready!"
echo "=========================================="
echo ""
echo "📦 Installed:"
echo "  - Go $(go version 2>/dev/null | awk '{print $3}' || echo 'not found')"
echo "  - Node.js $(node --version 2>/dev/null || echo 'not found')"
echo "  - npm $(npm --version 2>/dev/null || echo 'not found')"
echo "  - Jest $(jest --version 2>/dev/null || echo 'not found')"
echo "  - nano $(nano --version 2>/dev/null | head -n1 || echo 'not found')"
echo "  - Claude Code $(claude --version 2>/dev/null || echo 'not found')"
echo "  - Fly.io CLI $(flyctl version 2>/dev/null | head -n1 || echo 'not found')"
echo "  - uv $(uv --version 2>/dev/null || echo 'not found')"
echo "  - Supabase CLI (via npx supabase)"
echo "  - Playwright (Chromium)"
echo ""
echo "🛠️  Utilities:"
echo "  - jq $(jq --version 2>/dev/null || echo 'not found')"
echo "  - tree, htop, ncdu, vim, ss"
echo ""
echo "🔧 Configuration:"
echo "  - Git User: $(git config --global user.name 2>/dev/null || echo 'not configured')"
echo "  - Git Email: $(git config --global user.email 2>/dev/null || echo 'not configured')"
echo ""
echo "🛠️  Services (local Coder containers):"
echo "  - PostgreSQL: postgres:5432"
echo "  - Redis: redis:6379"
echo "  - Clerk: ${CLERK_TEST_SECRET_KEY:+TEST instance}${CLERK_TEST_SECRET_KEY:-using LIVE instance}"
echo "  - Email: Resend"
echo ""
echo "🚀 To Start Services:"
echo "  cd /home/coder/workspace/zmanim-lab"
echo "  ./.coder/start-services.sh"
echo ""
echo "  Or manually:"
echo "  - Web: cd web && npm run dev"
echo "  - API: cd api && go run cmd/api/main.go"
echo ""
echo "📋 Service Ports:"
echo "  - Web App: http://localhost:3001"
echo "  - Go API: http://localhost:8080"
echo "  - PostgreSQL: postgres:5432 (Docker network)"
echo "  - Redis: redis:6379 (Docker network)"
echo ""
echo "🧪 Testing:"
echo "  - Go tests: cd api && go test ./..."
echo "  - E2E tests: cd tests && npm run test:suite"
echo ""
echo "📚 Documentation:"
echo "  - Architecture: docs/architecture.md"
echo "  - Epics: docs/epics.md"
echo "  - README: README.md"
echo ""
echo "=========================================="

# Step 15: Run database migrations
print_status "Running database migrations..."
cd /home/coder/workspace/zmanim-lab
if [ -f "api/scripts/init-db.sh" ]; then
    chmod +x api/scripts/init-db.sh
    ./api/scripts/init-db.sh || print_warning "Migration failed - database may need manual setup"
    print_success "Database migrations complete"
else
    print_warning "init-db.sh not found - run migrations manually"
fi

# Step 16: Auto-start services
print_status "Starting services in background..."
cd /home/coder/workspace/zmanim-lab
if [ -f ".coder/start-services.sh" ]; then
    chmod +x .coder/start-services.sh
    ./.coder/start-services.sh --no-attach
    print_success "Services started in tmux session 'zmanim'"
    echo ""
    echo "🎯 Services are now running!"
    echo "   - Attach to tmux: tmux attach -t zmanim"
    echo "   - View API logs: tmux select-window -t zmanim:api"
    echo "   - View Web logs: tmux select-window -t zmanim:web"
else
    print_warning "start-services.sh not found - start services manually"
fi
