#!/bin/bash
set -e

# Zmanim Lab Development Environment Startup Script
# This script initializes the development environment for the monorepo

echo "🚀 Starting Zmanim Lab Development Environment Setup..."

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Fix workspace directory ownership (needed for Docker volumes)
sudo chown -R coder:coder /home/coder/workspace

# Change to workspace directory
cd /home/coder/workspace

# Step 1: Install Go 1.25.4 (latest)
print_status "Installing Go 1.25.4..."
if ! command -v go &> /dev/null || [[ $(go version | grep -o '1\.25\.4') == "" ]]; then
    wget -q https://go.dev/dl/go1.25.4.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf go1.25.4.linux-amd64.tar.gz
    rm go1.25.4.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    print_success "Go 1.25.4 installed"
else
    print_success "Go 1.25.4 already installed ($(go version))"
fi

# Step 2: Install Node.js 24.x LTS (Krypton - latest LTS)
print_status "Installing Node.js 24.x LTS..."
if ! command -v node &> /dev/null || [[ $(node --version | grep -o 'v24') == "" ]]; then
    curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
    sudo apt-get install -y nodejs
    print_success "Node.js 24.x LTS installed"
else
    print_success "Node.js 24.x LTS already installed ($(node --version))"
fi

# Step 3: Clone repository if it doesn't exist (monorepo)
print_status "Checking repository..."

# Add GitHub to known hosts
mkdir -p ~/.ssh
ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null

if [ ! -d "zmanim-lab/.git" ]; then
    print_status "Cloning zmanim-lab repository..."
    rm -rf zmanim-lab 2>/dev/null
    git clone ${ZMANIM_REPO:-git@github.com:jcom-dev/zmanim-lab.git} zmanim-lab || print_warning "Failed to clone zmanim-lab"
else
    print_success "zmanim-lab already cloned"
fi

# Checkout specified branch
if [ -n "${ZMANIM_BRANCH}" ] && [ "${ZMANIM_BRANCH}" != "main" ]; then
    print_status "Checking out branch '${ZMANIM_BRANCH}'..."
    cd zmanim-lab
    if git fetch origin "${ZMANIM_BRANCH}" 2>/dev/null && git checkout "${ZMANIM_BRANCH}" 2>/dev/null; then
        print_success "Checked out ${ZMANIM_BRANCH}"
    else
        print_warning "Branch ${ZMANIM_BRANCH} not found, staying on default"
    fi
    cd /home/coder/workspace
fi

# Step 4: Install Go dependencies
print_status "Installing Go dependencies..."
if [ -d "zmanim-lab/api" ]; then
    cd zmanim-lab/api
    go mod download || print_warning "Failed to download Go dependencies"
    cd /home/coder/workspace
    print_success "Go dependencies installed"
fi

# Step 5: Install Node.js dependencies
print_status "Installing Node.js dependencies..."
if [ -d "zmanim-lab/web" ]; then
    cd zmanim-lab/web
    npm install || print_warning "Failed to install web dependencies"
    cd /home/coder/workspace
    print_success "Web dependencies installed"
fi

# Step 6: Install Playwright browsers for E2E testing
print_status "Installing Playwright browsers..."
if [ -d "zmanim-lab/web" ]; then
    cd zmanim-lab/web
    npx playwright install --with-deps chromium || print_warning "Failed to install Playwright browsers"
    cd /home/coder/workspace
    print_success "Playwright browsers installed"
fi

# Step 7: Create .env files from Coder template variables
print_status "Setting up environment files from Coder variables..."
cd zmanim-lab

# Create api/.env from environment variables (set by Coder template)
if [ -n "$DATABASE_URL" ]; then
    cat > api/.env << ENVEOF
# Generated by Coder workspace startup
DATABASE_URL=${DATABASE_URL}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
CLERK_ISSUER=${CLERK_ISSUER}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001,https://localhost:3000,https://localhost:3001,https://127.0.0.1:3000,https://127.0.0.1:3001}
PORT=8080
GO_ENV=development
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success "api/.env created from Coder variables"
else
    print_warning "DATABASE_URL not set - copy .env.example to api/.env and configure"
    [ -f ".env.example" ] && [ ! -f "api/.env" ] && cp .env.example api/.env
fi

# Create web/.env.local from environment variables (set by Coder template)
if [ -n "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
    cat > web/.env.local << ENVEOF
# Generated by Coder workspace startup
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENVEOF
    print_success "web/.env.local created from Coder variables"
else
    print_warning "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY not set - copy .env.example to web/.env.local and configure"
    [ -f ".env.example" ] && [ ! -f "web/.env.local" ] && cp .env.example web/.env.local
fi

cd /home/coder/workspace

# Step 8: Install nano text editor
print_status "Installing nano text editor..."
if ! command -v nano &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y nano > /dev/null 2>&1
    print_success "nano installed"
else
    print_success "nano already installed"
fi

# Step 9: Install tmux for service management
print_status "Installing tmux..."
if ! command -v tmux &> /dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y tmux > /dev/null 2>&1
    print_success "tmux installed"
else
    print_success "tmux already installed"
fi

# Step 10: Install Fly.io CLI
print_status "Installing Fly.io CLI..."
if ! command -v flyctl &> /dev/null; then
    curl -L https://fly.io/install.sh | sh
    # Add to PATH for current session
    export FLYCTL_INSTALL="/home/coder/.fly"
    export PATH="$FLYCTL_INSTALL/bin:$PATH"
    echo 'export FLYCTL_INSTALL="/home/coder/.fly"' >> ~/.bashrc
    echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> ~/.bashrc
    print_success "Fly.io CLI installed"
else
    print_success "Fly.io CLI already installed"
fi

# Step 11: Install Claude Code CLI
print_status "Installing Claude Code..."
if ! command -v claude &> /dev/null; then
    curl -fsSL https://claude.ai/install.sh | bash
    # Add to PATH for current session
    export PATH="$HOME/.claude/bin:$PATH"
    echo 'export PATH="$HOME/.claude/bin:$PATH"' >> ~/.bashrc
    print_success "Claude Code installed"
else
    print_success "Claude Code already installed"
fi

# Step 12: Add claude alias to skip permissions
print_status "Adding claude alias to skip permissions..."
echo "alias claude='claude --dangerously-skip-permissions'" >> ~/.bashrc
print_success "Claude alias added"

# Step 13: Configure git user identity (with Coder variable overrides)
print_status "Configuring git user identity..."
GIT_USER_NAME="${GIT_USER_NAME:-Daniel Niasoff}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-4070285+dniasoff@users.noreply.github.com}"

git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
print_success "Git user configured: $GIT_USER_NAME <$GIT_USER_EMAIL>"

# Step 14: Display status
echo ""
echo "=========================================="
echo "✅ Zmanim Lab Development Environment Ready!"
echo "=========================================="
echo ""
echo "📦 Installed:"
echo "  - Go $(go version 2>/dev/null | awk '{print $3}' || echo 'not found')"
echo "  - Node.js $(node --version 2>/dev/null || echo 'not found')"
echo "  - npm $(npm --version 2>/dev/null || echo 'not found')"
echo "  - nano $(nano --version 2>/dev/null | head -n1 || echo 'not found')"
echo "  - Claude Code $(claude --version 2>/dev/null || echo 'not found')"
echo "  - Fly.io CLI $(flyctl version 2>/dev/null | head -n1 || echo 'not found')"
echo "  - Supabase CLI (via npx supabase)"
echo "  - Playwright (Chromium)"
echo ""
echo "🔧 Configuration:"
echo "  - Git User: $(git config --global user.name 2>/dev/null || echo 'not configured')"
echo "  - Git Email: $(git config --global user.email 2>/dev/null || echo 'not configured')"
echo ""
echo "🛠️  External Services (configure in .env):"
echo "  - Supabase: PostgreSQL database"
echo "  - Upstash: Redis caching"
echo "  - Clerk: Authentication"
echo "  - Resend: Transactional emails"
echo ""
echo "🚀 To Start Services:"
echo "  cd /home/coder/workspace/zmanim-lab"
echo "  ./.coder/start-services.sh"
echo ""
echo "  Or manually:"
echo "  - Web: cd web && npm run dev"
echo "  - API: cd api && go run cmd/api/main.go"
echo ""
echo "📋 Service Ports:"
echo "  - Web App: http://localhost:3001"
echo "  - Go API: http://localhost:8080"
echo ""
echo "🧪 Testing:"
echo "  - Go tests: cd api && go test ./..."
echo "  - E2E tests: cd web && npm run test:e2e"
echo ""
echo "📚 Documentation:"
echo "  - Architecture: docs/architecture.md"
echo "  - Epics: docs/epics.md"
echo "  - README: README.md"
echo ""
echo "=========================================="

# Step 15: Auto-start services
print_status "Starting services in background..."
cd /home/coder/workspace/zmanim-lab
if [ -f ".coder/start-services.sh" ]; then
    chmod +x .coder/start-services.sh
    ./.coder/start-services.sh --no-attach
    print_success "Services started in tmux session 'zmanim'"
    echo ""
    echo "🎯 Services are now running!"
    echo "   - Attach to tmux: tmux attach -t zmanim"
    echo "   - View API logs: tmux select-window -t zmanim:api"
    echo "   - View Web logs: tmux select-window -t zmanim:web"
else
    print_warning "start-services.sh not found - start services manually"
fi
